#!/usr/bin/env bash
set -euo pipefail

export PITGUARD_WORKER_DEFAULT_HARD_CAP_MB="${PITGUARD_WORKER_DEFAULT_HARD_CAP_MB:-6144}"
export PITGUARD_SUPPORT_CANDIDATE_TRIAL_LIMIT="${PITGUARD_SUPPORT_CANDIDATE_TRIAL_LIMIT:-9}"
export PITGUARD_SUPPORT_CANDIDATE_POOL_LIMIT="${PITGUARD_SUPPORT_CANDIDATE_POOL_LIMIT:-6}"
export PITGUARD_RUNTIME_DIAGNOSTICS="${PITGUARD_RUNTIME_DIAGNOSTICS:-1}"
export PITGUARD_RESOURCE_WATCH_INTERVAL_SECONDS="${PITGUARD_RESOURCE_WATCH_INTERVAL_SECONDS:-1}"
ROOT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
exec bash "$ROOT_DIR/scripts/build-and-start-production.sh" "$@"
